## Pkgs to be installed at the first time runnning the container. They're 
## being installed with just and the workspace-alpine.sh install script
go:
  - github.com/raviqqe/muffet/v2@latest
  - github.com/charmbracelet/glow@latest
  - github.com/muesli/duf@latest
  - github.com/exercism/cli/exercism@latest
## html5vali depends on java8
pipx:
  - epy-reader
  - streamlink
  - html5validator
npm:
  - browser-sync
sdk:
  - 8.0.302-open
