## Pkgs to be installed at the first time runnning the container. They're 
## being installed with just and the workspace-alpine.sh install script
go:
  - github.com/raviqqe/muffet/v2@latest
  - github.com/exercism/cli/exercism@latest
pipx:
  - epy-reader
  - streamlink
npm:
  - browser-sync
  - tldr
sdk:
  - 8.0.302-open
