##* Pkgs to be installed at the first time runnning the container. They're
##  being installed with just and the workspace-alpine.sh install script
##* asciinema from alpine doesn't work in a container => pipx does

## TODO Install linters via asdf
## Python: pylint mypy flake8 virtualenv
## webdev: eslint prettier stylelint stylelint-config-standard

## TODO If you ever need/care about Java. Research asdf java vs sdkman java
#and decide if it's worth to keep sdkman. Uninstalling it now and using
#asdf is too much work for I really don't care about it. But it'd be
#neat to have only one version manager. (from a short glimpse it seems
#that sdkman does not offer musl versions but asdf does, so ++ for asdf)

## TODO add all other tools to asdf
go:
  - github.com/raviqqe/muffet/v2@latest
  - github.com/charmbracelet/glow@latest
  - github.com/muesli/duf@latest
pipx:
  - asciinema
  - epy-reader
  - streamlink
  - vosk
npm:
  - browser-sync
sdk:
  - 8.0.302-open
asdf:
  #nodejs needs to be build from scratch with Alpine cause of musl, see zet
  - tools:
      name: golang
      url: https://github.com/asdf-community/asdf-golang.git
      ver:
        - latest
  - tools:
      name: gohugo
      url: https://github.com/nklmilojevic/asdf-hugo.git
      ver:
        - extended_0.120.3
